/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as identityContractSol from "./IdentityContract.sol";
export type { identityContractSol };
import type * as reputationContractSol from "./ReputationContract.sol";
export type { reputationContractSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { Identity } from "./IdentityContract.sol/Identity";
export { Identity__factory } from "./factories/IdentityContract.sol/Identity__factory";
export { Lock__factory } from "./factories/Lock__factory";
export type { IIdentityContract } from "./ReputationContract.sol/IIdentityContract";
export { IIdentityContract__factory } from "./factories/ReputationContract.sol/IIdentityContract__factory";
export type { ReputationContract } from "./ReputationContract.sol/ReputationContract";
export { ReputationContract__factory } from "./factories/ReputationContract.sol/ReputationContract__factory";
