/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as identityContractSol from "./IdentityContract.sol";
export * as reputationContractSol from "./ReputationContract.sol";
export { Lock__factory } from "./Lock__factory";
