/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IIdentityContract__factory } from "./IIdentityContract__factory";
export { ReputationContract__factory } from "./ReputationContract__factory";
