/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IIdentityContract } from "./IIdentityContract";
export type { ReputationContract } from "./ReputationContract";
